export const GET_STORY = 'story/GET_STORY';
export const GET_STORY_REQUEST = 'story/GET_STORY_REQUEST';
export const GET_STORY_SUCCESS = 'story/GET_STORY_SUCCESS';
export const GET_STORY_FAIL = 'story/GET_STORY_FAIL';

export const ADD_COMMENT = 'story/ADD_COMMENT';
export const ADD_COMMENT_REQUEST = 'story/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'story/ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'story/ADD_COMMENT_FAIL';

export const SET_COMMENT_RATING = 'story/SET_COMMENT_RATING';
export const SET_COMMENT_RATING_REQUEST = 'story/SET_COMMENT_RATING_REQUEST';
export const SET_COMMENT_RATING_SUCCESS = 'story/SET_COMMENT_RATING_SUCCESS';
export const SET_COMMENT_RATING_FAIL = 'story/SET_COMMENT_RATING_FAIL';

export const CLEAR_STORY = 'story/CLEAR_STORY';
