export const GET_MAIN_EVENTS_REVIEWS = 'main/GET_MAIN_EVENTS_REVIEWS';
export const GET_MAIN_EVENTS_REVIEWS_REQUEST = 'main/GET_MAIN_EVENTS_REVIEWS_REQUEST';
export const GET_MAIN_EVENTS_REVIEWS_SUCCESS = 'main/GET_MAIN_EVENTS_REVIEWS_SUCCESS';
export const GET_MAIN_EVENTS_REVIEWS_FAIL = 'main/GET_MAIN_EVENTS_REVIEWS_FAIL';

export const CLEAR_MAIN = 'main/CLEAR_MAIN';
