export const SET_AUTH = 'auth/SET_AUTH';

export const LOGIN = 'auth/LOGIN';
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'auth/LOGIN_FAIL';

export const REGISTER = 'auth/REGISTER';
export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'auth/REGISTER_FAIL';

export const QUICK_REGISTER = 'auth/QUICK_REGISTER';
export const QUICK_REGISTER_REQUEST = 'auth/QUICK_REGISTER_REQUEST';
export const QUICK_REGISTER_SUCCESS = 'auth/QUICK_REGISTER_SUCCESS';
export const QUICK_REGISTER_FAIL = 'auth/QUICK_REGISTER_FAIL';

export const CONFIRM_REGISTRATION = 'auth/CONFIRM_REGISTRATION';
export const CONFIRM_REGISTRATION_REQUEST = 'auth/CONFIRM_REGISTRATION_REQUEST';
export const CONFIRM_REGISTRATION_SUCCESS = 'auth/CONFIRM_REGISTRATION_SUCCESS';
export const CONFIRM_REGISTRATION_FAIL = 'auth/CONFIRM_REGISTRATION_FAIL';

export const SET_VALIDATION = 'auth/SET_VALIDATION';
export const CLEAR_VALIDATION = 'auth/CLEAR_VALIDATION';

export const CLEAR_AUTH = 'auth/CLEAR_AUTH';
