export const GET_USER_PROFILE = 'user/GET_USER_PROFILE';
export const GET_USER_PROFILE_REQUEST = 'user/GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'user/GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'user/GET_USER_PROFILE_FAIL';

export const CLEAR_USER = 'user/CLEAR_USER';
